spring:
  application:
    name: cloud-member-api

  cloud:
    aws:
      s3:
        bucket: cloud-member-s3-songi
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true
      parameterstore:
        enabled: true
        fail-fast: false

  datasource:
    driver-class-name: org.h2.Driver
    url: ${config.ecommerce.spring.datasource.url:jdbc:h2:mem:testdb}
    username: ${config.ecommerce.spring.datasource.username:sa}
    password: ${config.ecommerce.spring.datasource.password:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true


info:
  team-name: ${config.ecommerce.teamName:6조}



